### ISSUE TITLE
Running inside Docker container

### ISSUE THREAD

**Issue by derchrisuk** [Lange/node-elgato-stream-deck#34]
Hi,

I setup a Docker container, have the USB device passed into the container.
Here is a lsusb:

```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0fd9:0060 Elgato Systems GmbH
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

When I try to run one of the examples to access the Stream Deck, I get the following error:

```
/node_modules/node-hid/nodehid.js:24
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with path 0001:0003:00
    at new HID (/node_modules/node-hid/nodehid.js:24:17)
    at Object.<anonymous> (/node-elgato-stream-deck/index.js:290:33)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node-elgato-stream-deck/examples/fill-button-when-pressed.js:4:20)
```

Any idea what could be the problem here?
Some search results with the same error mentioned some user permission problems, and either a udev rule or running as root should help.

But I'm already root.
Anyone tried this inside a Docker container before?

**Comment by Lange** [comment]
Hi @derchrisuk!

That's an interesting issue. I have not personally attempted to use this module (nor any code which uses HID) in a Docker container before. I'm afraid that I'm unsure how to help here. 😕

**Comment by ProbablePrime** [comment]
This might be a bug within the upstream module `node-hid`.

A small reproduction script that just attempts to use `node-hid` within a docker container would confirm this.

**Comment by Julusian** [comment]
I can confirm that it is/will soon be possible to do this.
One caveat is that I am using a modded version of node-hid 0.7.8 (to use libusb), but once node-hid has fixed that is should be easily possible

The device needs to be passed in like the following, and libusb installed
`docker run -it --device=/dev/bus/usb/001/032 -v$PWD:/src node:8 bash`
