### ISSUE TITLE
getting syntaxyerror

### ISSUE THREAD

**Issue by ettr** [Lange/node-elgato-stream-deck#39]
Users/user/gitlab/decktest/node_modules/elgato-stream-deck/index.js:214
	async fillImageFromFile(keyIndex, filePath) {
	      ^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/gitlab/decktest/test.js:2:20)
    at Module._compile (module.js:570:32)

**Comment by Lange** [comment]
You need to use Node.js 7.6 or greater.
