### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by asdf23** [Lange/node-elgato-stream-deck#49]
As admin I am running
`npm install --global --production windows-build-tools`
`npm install --global node-gyp`
`npm install --save  elgato-stream-deck`

The last call throws this error

```
C:\elgato>npm install --save  elgato-stream-deck

> node-hid@0.6.0 install C:\elgato\node_modules\node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.0.0 runtime=node arch=x64 platform=win32)

C:\elgato\node_modules\node-hid>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  hid.c
  win_delay_load_hook.cc
  hidapi.vcxproj -> C:\elgato\node_modules\node-hid\build\Release\\hidapi.lib
  HID.cc
  win_delay_load_hook.cc
..\src\HID.cc(67): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow) [C:\el
gato\node_modules\node-hid\build\HID.vcxproj]
..\src\HID.cc(70): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow) [C:\el
gato\node_modules\node-hid\build\HID.vcxproj]
..\src\HID.cc(152): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow) [C:\e
lgato\node_modules\node-hid\build\HID.vcxproj]
..\src\HID.cc(163): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow) [C:\e
lgato\node_modules\node-hid\build\HID.vcxproj]
..\src\HID.cc(207): error C2661: 'v8::Function::NewInstance': no overloaded function takes 2 arguments [C:\elgato\node_modules\node-h
id\build\HID.vcxproj]
..\src\HID.cc(231): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\elgato\node_modules\node-hid\build\HID.vcxproj]
  C:\elgato\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
..\src\HID.cc(398): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\elgato\node_mo
dules\node-hid\build\HID.vcxproj]
..\src\HID.cc(409): warning C4996: 'v8::String::Value::Value': was declared deprecated [C:\elgato\node_modules\node-hid\build\HID.vcx
proj]
  c:\users\user1\.node-gyp\10.0.0\include\node\v8.h(2846): note: see declaration of 'v8::String::Value::Value'
..\src\HID.cc(488): warning C4244: 'argument': conversion from 'wchar_t' to 'char', possible loss of data [C:\elgato\node_modules\nod
e-hid\build\HID.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\elgato\node_modules\node-hid
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\elgato\package.json'
npm WARN elgato No description
npm WARN elgato No repository field.
npm WARN elgato No README data
npm WARN elgato No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-04-25T21_29_11_609Z-debug.log

C:\elgato>npm install --save  node-elgato-stream-desk
npm ERR! code E404
npm ERR! 404 Not Found: node-elgato-stream-desk@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-04-25T21_30_45_194Z-debug.log

C:\elgato>
```

**Comment by Lange** [comment]
I don't think Node.js 9 or 10 is supported by the version of `node-hid` that we use. Are you able to use Node.js 8?

**Comment by asdf23** [comment]
8 is working as you suspected, thanks
