### ISSUE TITLE
async fillImageFromFile(keyIndex, filePath) -> SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by YuriStruszczynski** [Lange/node-elgato-stream-deck#54]
Hi,

i get the following error, any ideas how to fix this?

```
PS C:\Users\XYZ\Desktop\nodejs\streamdeck> node run.js
C:\Users\XYZ\node_modules\elgato-stream-deck\index.js:214
        async fillImageFromFile(keyIndex, filePath) {
              ^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\XYZ\Desktop\nodejs\streamdeck\run.js:2:20)
    at Module._compile (module.js:570:32)
```

Best regards, Yuri

**Comment by Lange** [comment]
Hi Yuri,

You'll need to use Node.js 7 or newer.

**Comment by YuriStruszczynski** [comment]
THX, i installed nvm to get ability to switch to 7 but got a lot of different other errors not related to this projects code. I think i have to try it on a blank system. Best regards, Yuri
