### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by justweb1** [Lange/node-elgato-stream-deck#55]
Console Output:
```
D:\FiveM\fxserver-data\resources\nodejs>npm i --save elgato-stream-deck

> node-hid@0.6.0 install D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.2.1 runtime=node arch=x64 platform=win32)

D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  hid.c
  win_delay_load_hook.cc
  hidapi.vcxproj -> D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid\build\Release\\hidapi.lib
  HID.cc
  win_delay_load_hook.cc
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(67): warning C4290: C++ exception specificatio
n ignored except to indicate a function is not __declspec(nothrow) [D:\FiveM\fxserver-data\resources\nodejs\node_module
s\node-hid\build\HID.vcxproj]
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(70): warning C4290: C++ exception specificatio
n ignored except to indicate a function is not __declspec(nothrow) [D:\FiveM\fxserver-data\resources\nodejs\node_module
s\node-hid\build\HID.vcxproj]
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(152): warning C4290: C++ exception specificati
on ignored except to indicate a function is not __declspec(nothrow) [D:\FiveM\fxserver-data\resources\nodejs\node_modul
es\node-hid\build\HID.vcxproj]
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(163): warning C4290: C++ exception specificati
on ignored except to indicate a function is not __declspec(nothrow) [D:\FiveM\fxserver-data\resources\nodejs\node_modul
es\node-hid\build\HID.vcxproj]
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(207): error C2661: 'v8::Function::NewInstance'
: no overloaded function takes 2 arguments [D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid\build\HID.vcx
proj]
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(231): warning C4996: 'Nan::Callback::Call': wa
s declared deprecated [D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid\build\HID.vcxproj]
  d:\fivem\fxserver-data\resources\nodejs\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(398): warning C4530: C++ exception handler use
d, but unwind semantics are not enabled. Specify /EHsc [D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid\b
uild\HID.vcxproj]
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(409): warning C4996: 'v8::String::Value::Value
': was declared deprecated [D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid\build\HID.vcxproj]
  c:\users\justi\.node-gyp\10.2.1\include\node\v8.h(2846): note: see declaration of 'v8::String::Value::Value'
d:\fivem\fxserver-data\resources\nodejs\node_modules\node-hid\src\hid.cc(488): warning C4244: 'argument': conversion fr
om 'wchar_t' to 'char', possible loss of data [D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid\build\HID.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\FiveM\fxserver-data\resources\nodejs\node_modules\node-hid
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN nodejs@1.0.0 No description
npm WARN nodejs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\justi\AppData\Roaming\npm-cache\_logs\2018-07-21T18_34_30_710Z-debug.log
```

NPM Debug Log: (these are the only errors I found)
```
2108 error code ELIFECYCLE
2109 error errno 1
2110 error node-hid@0.6.0 install: `prebuild-install || node-gyp rebuild`
2110 error Exit status 1
2111 error Failed at the node-hid@0.6.0 install script.
2111 error This is probably not a problem with npm. There is likely additional logging output above.
2112 verbose exit [ 1, true ]
```

**Comment by Lange** [comment]
Hi @justweb1,

Are perhaps you having the same issue as https://github.com/Lange/node-elgato-stream-deck/issues/49?

**Comment by justweb1** [comment]
My error is a little different but I will try downgrading Node.

**Comment by justweb1** [comment]
Reverting to Node v8 did resolve the issue. 
Thanks @Lange .
