### ISSUE TITLE
Streamdeck XL cannot use the resetToLogo

### ISSUE THREAD

**Issue by Eastborn** [Lange/node-elgato-stream-deck#68]
Whenever i try to call StreamDeck.resetToLogo() on a streamdeck XL: 
My code:
```typescript
deck.on("down", key => {
    console.log(`${device.model}:${device.serialNumber} -> ${key}`);
    if (key == 30 && device.serialNumber == "CL18I1A04711") {
        deck.resetToLogo();
    }
});
```
The stack trace
```
\node_modules\elgato-stream-deck\dist\models\xl.js:41
        this.device.sendFeatureReport(resetCommandBuffer);
                    ^
Error: could not send feature report to device
    at StreamDeckXL.resetToLogo (\node_modules\elgato-stream-deck\dist\models\xl.js:41:21)
    at StreamDeckXL.<anonymous> (\src\Install.ts:35:26)
    at StreamDeckXL.emit (events.js:203:13)
    at HID.<anonymous> (\node_modules\elgato-stream-deck\dist\models\base.js:41:30)
    at HID.emit (events.js:203:13)
    at readFunc (\node_modules\node-hid\nodehid.js:120:22)
```
which would be this code: 
models/xl.js:36-42
```javascript
resetToLogo() {
    // prettier-ignore
    const resetCommandBuffer = [
        0x03, 0x02
    ];
    this.device.sendFeatureReport(resetCommandBuffer);
}
```

**Comment by Julusian** [comment]
Sorry for the delay.
This is resolved in v3.1.0
