### ISSUE TITLE
node-hid issues on linux when using Stream Deck XL

### ISSUE THREAD

**Issue by monoxane** [Lange/node-elgato-stream-deck#81]
Trying to use my new XL to work on a project, it works fine on macOS on an identical code base, but fails to connect on Linux.

I have done [this](https://github.com/Lange/node-elgato-stream-deck#linux) but it did not fix the issue.

Running the following:
Linux [hostname] 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
Node v13.5.0
elgato-stream-deck 3.2.0

Error:
```
(node:7303) UnhandledPromiseRejectionWarning: Error: cannot open device with path 0001:0002:00
    at new HID (/home/monoxane/Development/BorealDirector/node_modules/node-hid/nodehid.js:49:17)
    at new StreamDeckBase (/home/monoxane/Development/BorealDirector/node_modules/elgato-stream-deck/dist/models/base.js:12:23)
    at new StreamDeckGen2Base (/home/monoxane/Development/BorealDirector/node_modules/elgato-stream-deck/dist/models/base-gen2.js:9:1)
    at new StreamDeckXL (/home/monoxane/Development/BorealDirector/node_modules/elgato-stream-deck/dist/models/xl.js:15:9)
    at openStreamDeck (/home/monoxane/Development/BorealDirector/node_modules/elgato-stream-deck/dist/index.js:78:12)
    at /home/monoxane/Development/BorealDirector/core/libs/controllers/providers/elgato-streamdeck.js:35:24
    at new Promise (<anonymous>)
    at connectStreamDecks (/home/monoxane/Development/BorealDirector/core/libs/controllers/providers/elgato-streamdeck.js:12:10)
    at Object.<anonymous> (/home/monoxane/Development/BorealDirector/core/libs/controllers/controllerManager.js:6:1)
    at Generator.next (<anonymous>)
(node:7303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7303) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Julusian** [comment]
This is a strange issue, I generally run on Ubuntu and have not had problems like this.
All I can suggest right now is to double check you followed the udev instructions correctly and then perhaps restart your pc to ensure that it is being applied.

Otherwise, do you have anything else running which may be trying to use the usb device? I think I have found that other things can mess it up if they try to open the device with the other type of usb-hid driver.

**Comment by monoxane** [comment]
It looks like it was something trying to bind to that specific USB port on my system even after rebooting, moving the Stream Deck XL to a different USB port works as expected.
